" ----------------------------------------------------------------------------
" file:     ~/.vimrc
" author:   Daniel Henschel - http://is-bored.de/
" modified: June 2013
" vim:      si:et:ts=4:sw=4:ft=vim
" ----------------------------------------------------------------------------

" general config -------------------------------------------------------------
set nocompatible                    " don't be conpatible to vi
set number                          " show line numbers
set backspace=indent,eol,start      " allow backspace in insert mode
set history=1000                    " more history
set showcmd                         " show incomplete normal mode commands
syntax on                           " syntax highlighting
let mapleader=","                   " change the leader to ,

" load plugins ---------------------------------------------------------------
filetype off                        " required by vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Plugin 'gmarik/vundle'
Plugin 'altercation/vim-colors-solarized'
Plugin 'Lokaltog/powerline'
filetype plugin indent on           " enable loading indent file for filetype

" turn off swap and .viminfo
set noswapfile
set nobackup
set nowb
set viminfo=""

" persistent undo
set undodir=~/.vim/backups
set undofile

" indentation
set autoindent                      " always set autoindenting on
set smartindent                     " use smart indent if ther is no file
set smarttab                        " smart tabbing
set shiftwidth=4                    " indent level = 4 spaces
set softtabstop=4                   " backspace fake tabs
set tabstop=4                       " <tab> = 4 spaces
set expandtab                       " use spaces instead of tabs

" folds
set foldmethod=indent               " fold based on indent
set foldnestmax=3                   " deepest is 3 levels
set nofoldenable                    " don't fold by default

" scrolling
set scrolloff=8                     " keep 8 lines of context

" completion
set wildmenu                        " menu completion in command mode on <Tab>
set wildmode=list:longest           " behave like shell
set wildignore+=*.o,*.obj,.git,*.pyc    " ignore these when completing

" search
set smartcase                       " ignore lowercase but uppercase
set hlsearch                        " highlight results
set incsearch                       " search as i type

" stuff
set cursorline                      " highlight current line
set mouse=a                         " use mouse
set nowrap                          " don't wrap lines
set linebreak                       " break lines at convenient points
set list listchars=tab:\ \ ,trail:· " show trailing whitespace

" plugin config -------------------------------------------------------------
" altercation/vim-colors-solarized
set background=dark
colorscheme solarized

" Lokaltog/powerline
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
set laststatus=2                    " always show powerline
set noshowmode                      " hide current mode
