function start_gpg_agent() {
    local gpg_env="$XDG_CACHE_HOME/gpg-env"

    if ! (( $+commands[gpg-agent] )); then
        return
    fi

    if ! pgrep gpg-agent >/dev/null; then
        gpg-agent --daemon > "$gpg_env"
    fi

    source "$gpg_env"
}

start_gpg_agent

if [[ $TTY == /dev/tty1 ]] && [[ -z $DISPLAY ]]; then
    exec startx
fi
